class _BotCommands:
    def __init__(self):
        self.StartCommand = 'startVision'
        self.MirrorCommand = 'vision'
        self.UnzipMirrorCommand = 'unzipmirror'
        self.TarMirrorCommand = 'tarmirror'
        self.ZipMirrorCommand = 'zipmirror'
        self.CancelMirror = 'cancelVision'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'listVision'
        self.StatusCommand = 'statusVision'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'pingVision'
        self.RestartCommand = 'restartVision'
        self.StatsCommand = 'statsVision'
        self.HelpCommand = 'helpVision'
        self.LogCommand = 'logVision'
        self.SpeedCommand = 'speedtestVision'
        self.CloneCommand = 'clone'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch'
        self.TarWatchCommand = 'tarwatch'
        self.DeleteCommand = 'del'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'

BotCommands = _BotCommands()
